### ISSUE TITLE
Successful run, but no data

### ISSUE THREAD

**Issue by torvenkat** [timatooth/gofit#3]
Hello, First thanks for the great code.  This has a lot of promise in fitbit data visualization.  I am able to successfully run it.  I get

```
Loading step data into influxdb...
Done loading steps
Loading resting heartrate data
Done
Loading 30 days of 1s intraday heartrate data...
Loading: 2018-06-22
Loading: 2018-06-21
Loading: 2018-05-24
Done
```
It does not return to the terminal prompt, but just hangs there. 
And when try to look into my data at influxdb (using chronograf interface)

`SELECT mean("steps") AS "mean_steps" FROM "fitbit"."autogen"."activity_steps" WHERE time > :dashboardTime: AND "steps"='steps-total' GROUP BY time(:interval:) FILL(null)`

I get the following error

`unsupported mean iterator type: *query.stringInterruptIterator`

When I look into the raw data, there are just a few numbers.   Will greatly appreciate your help.

**Comment by timatooth** [comment]
Hmm it's been quite a while since I've used Influx.  I'm not sure if the structure of the fitbit data may have changed which could be breaking something or the influx client library (since 1.2 i used) is processing data types differently.

`unsupported mean iterator type: *query.stringInterruptIterator` sounds like it's trying to calculate the mean on a string datatype field.

Perhaps `SHOW FIELD KEYS [ON <database_name>] [FROM <measurement_name>]`  to show the schema layout/datatypes may shed some light? https://docs.influxdata.com/influxdb/v1.5/query_language/schema_exploration/#show-field-keys

I lost my Charge HR2 a while back so I'm not really able test it using the latest versions.

**Comment by timatooth** [comment]
@torvenkat did you get any further with debugging this? Regarding the terminal 'hanging' behavior, that's expected since it's running a web server for getting the callback from fitbit during authorisation.
